# Generated by Django 3.2 on 2021-04-23 07:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_email_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='题目名称')),
                ('message', models.TextField(verbose_name='题目描述信息')),
                ('inputs', models.TextField(blank=True, null=True, verbose_name='题目输入流')),
                ('correct_outs', models.TextField(verbose_name='题目正确输入信息')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='题目作者', to=settings.AUTH_USER_MODEL, verbose_name='题目作者')),
            ],
            options={
                'ordering': ['-create_date'],
            },
        ),
    ]
