# Generated by Django 3.2 on 2021-04-23 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210423_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='solved_problems',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='已解决的题', to='api.problem', verbose_name='已解决的题'),
        ),
    ]
