# Generated by Django 3.2 on 2021-04-23 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_participant_solved_problems'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='alg_type',
            field=models.CharField(choices=[('b', '基础'), ('g', '贪心算法')], default='b', max_length=1, verbose_name='算法类型'),
        ),
        migrations.AddField(
            model_name='problem',
            name='ds_type',
            field=models.CharField(choices=[('b', '基础'), ('a', '数组')], default='b', max_length=1, verbose_name='数据结构类型'),
        ),
    ]
