# Generated by Django 3.2 on 2021-04-23 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20210423_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='alg_type',
            field=models.CharField(choices=[('b', '基础'), ('g', '贪心算法'), ('f', 'DFS/BFS'), ('x', '动态规划'), ('t', '二分法'), ('d', '最短路径算法')], default='b', max_length=1, verbose_name='算法类型'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='ds_type',
            field=models.CharField(choices=[('b', '基础'), ('a', '数组'), ('l', '链表'), ('s', '栈'), ('q', '队列'), ('h', '哈希表'), ('t', '树'), ('p', '图')], default='b', max_length=1, verbose_name='数据结构类型'),
        ),
    ]
