# Generated by Django 3.2 on 2021-04-24 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20210423_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='header',
            field=models.CharField(choices=[('a', '入门'), ('b', '简单'), ('c', '中等'), ('d', '困难'), ('e', '特难')], default='a', max_length=1, verbose_name='难度'),
        ),
    ]
