# Generated by Django 3.2 on 2021-04-26 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20210426_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='context',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='出题方', to='api.competitionorganizer', verbose_name='机构'),
        ),
    ]
