# Generated by Django 3.2 on 2021-04-27 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_context_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='init_code',
            field=models.TextField(default='class Solution:\n"""\n@param a: An integer\n@param b: An integer\n@return: The sum of a and b\n"""\ndef function(self, a, b):\n    # write your code here\n    ', verbose_name='题目初始化显示'),
        ),
        migrations.AddField(
            model_name='problem',
            name='test_code',
            field=models.TextField(default='\ndata_in_lst = {0}\ndata_cor_output_lst = {1}\n\ns = Solution()\nfor i in range(len(data_in_lst)):\n    assert s.function(data_in_lst[i]) == data_cor_output_lst[i]\n', verbose_name='题目测试代码文本部分'),
        ),
    ]
