# Generated by Django 3.2 on 2021-04-27 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20210427_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='init_code',
            field=models.TextField(default='class Solution:\n    """\n    @param a: An integer\n    @param b: An integer\n    @return: The sum of a and b\n    """\n    def function(self, a, b):\n        # write your code here\n        ', verbose_name='题目初始化显示'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='test_code',
            field=models.TextField(default='\ns = Solution()\nfor i in range(len(data_in_lst)):\n    assert s.function(data_in_lst[i]) == data_cor_output_lst[i]\n', verbose_name='题目测试代码文本部分'),
        ),
    ]
