# Generated by Django 3.2 on 2021-04-27 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20210427_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='correct_outs',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='inputs',
        ),
    ]
