# Generated by Django 3.2 on 2021-04-28 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20210427_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='solved_problems',
        ),
        migrations.AddField(
            model_name='participant',
            name='solved_problems',
            field=models.ManyToManyField(blank=True, null=True, to='api.Problem', verbose_name='已解决的题'),
        ),
    ]
