# Generated by Django 3.2 on 2021-05-04 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20210505_0130'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
