# Generated by Django 3.2 on 2021-05-04 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_problem_public'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='比赛名称')),
                ('message', models.TextField(verbose_name='比赛描述信息')),
                ('sign_up_start_date', models.DateTimeField(help_text='Format is: yyyy-mm-dd hh:mm', verbose_name='报名开始时间')),
                ('sign_up_end_date', models.DateTimeField(help_text='Format is: yyyy-mm-dd hh:mm', verbose_name='报名结束时间')),
                ('competition_start_date', models.DateTimeField(help_text='Format is: yyyy-mm-dd hh:mm', verbose_name='比赛开始时间')),
                ('competition_end_date', models.DateTimeField(help_text='Format is: yyyy-mm-dd hh:mm', verbose_name='比赛结束时间')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='出题方', to='api.competitionorganizer', verbose_name='机构')),
            ],
            options={
                'verbose_name': '比赛（competition）',
                'verbose_name_plural': '比赛（competition）',
                'ordering': ['-sign_up_start_date', '-sign_up_end_date', '-competition_start_date', '-competition_end_date'],
            },
        ),
        migrations.AlterField(
            model_name='problem',
            name='public',
            field=models.BooleanField(default=True, verbose_name='是否公开'),
        ),
        migrations.DeleteModel(
            name='Context',
        ),
        migrations.AddField(
            model_name='competition',
            name='problems',
            field=models.ManyToManyField(to='api.Problem'),
        ),
    ]
