# Generated by Django 3.2 on 2021-05-04 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_rename_competition_contest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contest',
            options={'ordering': ['-sign_up_start_date', '-sign_up_end_date', '-contest_start_date', '-contest_end_date'], 'verbose_name': '比赛（contest）', 'verbose_name_plural': '比赛（contest）'},
        ),
        migrations.RenameField(
            model_name='contest',
            old_name='competition_end_date',
            new_name='contest_end_date',
        ),
        migrations.RenameField(
            model_name='contest',
            old_name='competition_start_date',
            new_name='contest_start_date',
        ),
    ]
