# Generated by Django 3.2 on 2021-05-05 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_auto_20210505_0553'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='sign_up_contests',
            field=models.ManyToManyField(blank=True, to='api.Contest', verbose_name='已报名的竞赛'),
        ),
    ]
