# Generated by Django 3.2 on 2021-05-05 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_participant_sign_up_contests'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CompetitionOrganizer',
            new_name='ContestOrganizer',
        ),
    ]
