# Generated by Django 3.2 on 2021-05-05 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_rename_competitionorganizer_contestorganizer'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='requirement',
            field=models.TextField(blank=True, verbose_name='比赛要求信息'),
        ),
        migrations.AddField(
            model_name='contest',
            name='reward',
            field=models.TextField(default='', verbose_name='比赛奖励信息'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='message',
            field=models.TextField(default='', verbose_name='比赛描述信息'),
        ),
    ]
