# Generated by Django 3.2 on 2021-05-06 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_auto_20210506_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='init_code',
            field=models.TextField(default='class Solution:\n    """\n    @param a: An integer\n    @param b: An integer\n    @return: The sum of a and b \n    """\n    def aplusb(self, a, b):\n        # write your code here\n        ', verbose_name='题目初始化显示'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='test_code',
            field=models.TextField(default="inputs = [[1,2],[100,200],[-3,-1],[0,3]]\ncorrects= [3,300,-4,3]\n\nif len(inputs) != len(corrects):\n    raise Exception('题目测试集错误，请联系管理员进行重修审核')\n\ns = Solution()\nfor i in range(len(inputs)):\n    params = inputs[i]\n    if s.aplusb(params[0], params[1]) != corrects[i]:\n        raise Exception('输入值:{0}, {1}. 不等于正确值:{2}'.format(params[0],params[1],corrects[i]))\n", verbose_name='题目测试代码文本部分'),
        ),
    ]
