# Generated by Django 3.2 on 2021-05-06 01:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_auto_20210506_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='sign_up_user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
