# Generated by Django 3.2 on 2021-05-06 01:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_contest_sign_up_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='sign_up_user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='报名的人'),
        ),
    ]
