# Generated by Django 3.2 on 2021-05-06 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_user_is_admin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forumreply',
            options={'ordering': ['-publish_date', '-fid', '-author'], 'verbose_name': '论坛回复（reply）', 'verbose_name_plural': '论坛回复（reply）'},
        ),
    ]
