# Generated by Django 3.2 on 2021-05-06 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_alter_forumreply_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='like_cnt',
            field=models.IntegerField(default=0, verbose_name='点赞'),
        ),
    ]
