# Generated by Django 3.2 on 2021-05-06 09:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_forum_like_cnt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forum',
            name='like_cnt',
        ),
        migrations.AddField(
            model_name='forum',
            name='like_cnt',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='点赞'),
        ),
    ]
