# Generated by Django 3.2 on 2021-05-07 18:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_auto_20210506_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='sign_up_user',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='报名的人'),
        ),
        migrations.DeleteModel(
            name='Article',
        ),
    ]
