# Generated by Django 3.2 on 2021-05-08 18:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_alter_participant_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='finished_contests',
            field=models.ManyToManyField(blank=True, related_name='finished_contests', to='api.Contest', verbose_name='已完成的竞赛'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='sign_up_contests',
            field=models.ManyToManyField(blank=True, related_name='signed_contests', to='api.Contest', verbose_name='已报名的竞赛'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
