# Generated by Django 3.2.1 on 2021-05-09 14:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_auto_20210508_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='contest_end_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 9, 14, 46, 46, 829177), help_text='Format is: yyyy-mm-dd hh:mm', verbose_name='比赛结束时间'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='contest_start_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 9, 14, 46, 46, 829177), help_text='Format is: yyyy-mm-dd hh:mm', verbose_name='比赛开始时间'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='sign_up_end_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 9, 14, 46, 46, 829177), help_text='Format is: yyyy-mm-dd hh:mm', verbose_name='报名结束时间'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='sign_up_start_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 9, 14, 46, 46, 829177), help_text='Format is: yyyy-mm-dd hh:mm', verbose_name='报名开始时间'),
        ),
    ]
