# Generated by Django 3.2 on 2021-05-10 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_auto_20210510_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='is_wait',
            field=models.BooleanField(default=False, verbose_name='等待中'),
        ),
    ]
