# Generated by Django 3.2 on 2021-05-10 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_auto_20210510_1600'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContestResult',
            new_name='ContestRankingResult',
        ),
        migrations.AlterModelOptions(
            name='contestrankingresult',
            options={'ordering': ['-ranking'], 'verbose_name': '比赛-用户-排名记录（Contest Ranking Result）', 'verbose_name_plural': '比赛-用户-排名记录（Contest Ranking Result）'},
        ),
        migrations.CreateModel(
            name='ContestInfoResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contest_info', to='api.contest', verbose_name='比赛题目')),
                ('pass_problem', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.problem', verbose_name='用户完成题目')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_info', to=settings.AUTH_USER_MODEL, verbose_name='比赛参与用户')),
            ],
            options={
                'verbose_name': '比赛-用户-解决题目记录（Contest Info Result）',
                'verbose_name_plural': '比赛-用户-解决题目记录（Contest Info Result）',
            },
        ),
    ]
