# Generated by Django 3.2 on 2021-05-11 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_auto_20210510_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='题号'),
        ),
    ]
