# Generated by Django 3.2 on 2021-05-11 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_contestinforesult_spend_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contestinforesult',
            name='pass_problem',
        ),
        migrations.AddField(
            model_name='contestinforesult',
            name='pass_problems',
            field=models.ManyToManyField(to='api.Problem', verbose_name='用户完成题目'),
        ),
    ]
