# Generated by Django 3.2.3 on 2021-06-16 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_auto_20210511_1739'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_oc',
            new_name='is_o',
        ),
        migrations.RemoveField(
            model_name='contestorganizer',
            name='email',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_p',
            field=models.BooleanField(default=False, verbose_name='是否 竞赛参与者'),
        ),
    ]
